# Generated by Django 3.2.9 on 2021-12-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='课程名字')),
                ('address', models.CharField(max_length=20, verbose_name='上课地点')),
                ('term', models.IntegerField(choices=[(1, '上学期'), (2, '下学期')], default=1, verbose_name='学期')),
            ],
            options={
                'verbose_name': '课程管理',
                'verbose_name_plural': '课程管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='学号')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('nickname', models.CharField(max_length=10, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '学生管理',
                'verbose_name_plural': '学生管理',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='工号')),
                ('nickname', models.CharField(max_length=10, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '教师管理',
                'verbose_name_plural': '教师管理',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课管理',
                'verbose_name_plural': '选课管理',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name='授课教师'),
        ),
    ]
