# Generated by Django 3.2.9 on 2021-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
